/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/prescriptions/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Approve or reject a prescription
         * @description Required access: ADMIN.
         */
        put: operations["reviewPrescription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update order status
         * @description Required access: ADMIN.
         */
        put: operations["updateOrderStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Admin cancel an order
         * @description Required access: ADMIN.
         */
        put: operations["cancelOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medicine by ID
         * @description Required access: ADMIN.
         */
        get: operations["getMedicineById"];
        /**
         * Update medicine details
         * @description Required access: ADMIN.
         */
        put: operations["updateMedicine"];
        post?: never;
        /**
         * Soft-delete a medicine
         * @description Required access: ADMIN.
         */
        delete: operations["deleteMedicine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category by ID
         * @description Required access: ADMIN.
         */
        get: operations["getCategoryById"];
        /**
         * Update a category
         * @description Required access: ADMIN.
         */
        put: operations["updateCategory"];
        post?: never;
        /**
         * Soft-delete a category
         * @description Required access: ADMIN.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all medicines (active + inactive)
         * @description Required access: ADMIN.
         */
        get: operations["getAllMedicines"];
        put?: never;
        /**
         * Add a new medicine to the catalog
         * @description Required access: ADMIN.
         */
        post: operations["addMedicine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all categories
         * @description Required access: ADMIN.
         */
        get: operations["getAllCategories"];
        put?: never;
        /**
         * Create a new category
         * @description Required access: ADMIN.
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update stock quantity
         * @description Required access: ADMIN.
         */
        patch: operations["updateStock"];
        trace?: never;
    };
    "/api/admin/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sales report for a date range
         * @description Required access: ADMIN.
         */
        get: operations["getSalesReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/sales/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's sales report
         * @description Required access: ADMIN.
         */
        get: operations["getTodaySalesReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/sales/this-month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current month's sales report
         * @description Required access: ADMIN.
         */
        get: operations["getThisMonthSalesReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prescription volume report
         * @description Required access: ADMIN.
         */
        get: operations["getPrescriptionReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full inventory report
         * @description Required access: ADMIN.
         */
        get: operations["getInventoryReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export sales report as CSV or PDF
         * @description Required access: ADMIN.
         */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all prescriptions (paginated)
         * @description Required access: ADMIN.
         */
        get: operations["getAllPrescriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prescriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single prescription by ID
         * @description Required access: ADMIN.
         */
        get: operations["getPrescriptionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prescriptions/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get pending prescription review queue
         * @description Required access: ADMIN.
         */
        get: operations["getPendingPrescriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/prescriptions/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get pending prescription count
         * @description Required access: ADMIN.
         */
        get: operations["getPrescriptionCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all orders (paginated, newest first)
         * @description Required access: ADMIN.
         */
        get: operations["getAllOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single order with all items
         * @description Required access: ADMIN.
         */
        get: operations["getOrderById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all orders for a specific user
         * @description Required access: ADMIN.
         */
        get: operations["getOrdersByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get orders filtered by status
         * @description Required access: ADMIN.
         */
        get: operations["getOrdersByStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active orders that need admin attention
         * @description Required access: ADMIN.
         */
        get: operations["getActiveOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search medicines by name, generic name, or manufacturer
         * @description Required access: ADMIN.
         */
        get: operations["searchMedicines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/category/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medicines by category
         * @description Required access: ADMIN.
         */
        get: operations["getMedicinesByCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/alerts/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get quick inventory alert counts
         * @description Required access: ADMIN.
         */
        get: operations["getAlertSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/alerts/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medicines with low stock
         * @description Required access: ADMIN.
         */
        get: operations["getLowStockMedicines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/alerts/expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medicines expiring within 30 days
         * @description Required access: ADMIN.
         */
        get: operations["getExpiringMedicines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/alerts/expired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medicines already expired
         * @description Required access: ADMIN.
         */
        get: operations["getExpiredMedicines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/medicines/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active medicines only
         * @description Required access: ADMIN.
         */
        get: operations["getActiveMedicines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full dashboard data
         * @description Required access: ADMIN.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active categories only
         * @description Required access: ADMIN.
         */
        get: operations["getActiveCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PrescriptionReviewDto: {
            decision: string;
            rejectionReason?: string;
        };
        ApiResponsePrescriptionResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PrescriptionResponseDto"];
            timestamp?: string;
        };
        PrescriptionResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            userEmail?: string;
            fileUrl?: string;
            fileType?: string;
            status?: string;
            doctorName?: string;
            doctorRegNumber?: string;
            /** Format: int64 */
            reviewedByAdminId?: number;
            rejectionReason?: string;
            /** Format: int64 */
            orderId?: number;
            uploadedAt?: string;
            reviewedAt?: string;
        };
        OrderStatusUpdateDto: {
            status: string;
            adminNote?: string;
        };
        ApiResponseOrderResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["OrderResponseDto"];
            timestamp?: string;
        };
        OrderItemResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            medicineId?: number;
            medicineName?: string;
            medicineStrength?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: double */
            unitPrice?: number;
            /** Format: double */
            totalPrice?: number;
        };
        OrderResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            userEmail?: string;
            userName?: string;
            status?: string;
            /** Format: double */
            totalAmount?: number;
            /** Format: double */
            discountAmount?: number;
            /** Format: double */
            taxAmount?: number;
            /** Format: double */
            deliveryCharge?: number;
            items?: components["schemas"]["OrderItemResponseDto"][];
            deliveryAddress?: string;
            pincode?: string;
            deliverySlot?: string;
            /** Format: int64 */
            prescriptionId?: number;
            adminNote?: string;
            paymentMethod?: string;
            paymentId?: string;
            createdAt?: string;
            updatedAt?: string;
            deliveredAt?: string;
        };
        MedicineRequestDto: {
            name: string;
            genericName?: string;
            manufacturer?: string;
            dosageForm?: string;
            strength?: string;
            /** Format: double */
            price: number;
            /** Format: double */
            mrp?: number;
            /** Format: int32 */
            stock: number;
            requiresPrescription?: boolean;
            /** Format: int64 */
            categoryId: number;
            imageUrl?: string;
            description?: string;
            expiryDate: string;
            sku?: string;
        };
        ApiResponseMedicineResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MedicineResponseDto"];
            timestamp?: string;
        };
        MedicineResponseDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            genericName?: string;
            manufacturer?: string;
            dosageForm?: string;
            strength?: string;
            /** Format: double */
            price?: number;
            /** Format: double */
            mrp?: number;
            /** Format: int32 */
            stock?: number;
            requiresPrescription?: boolean;
            expiryDate?: string;
            /** Format: int64 */
            categoryId?: number;
            categoryName?: string;
            imageUrl?: string;
            description?: string;
            sku?: string;
            createdAt?: string;
            updatedAt?: string;
            active?: boolean;
        };
        CategoryRequestDto: {
            name: string;
            description?: string;
            imageUrl?: string;
        };
        ApiResponseCategoryResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CategoryResponseDto"];
            timestamp?: string;
        };
        CategoryResponseDto: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            imageUrl?: string;
            createdAt?: string;
            active?: boolean;
        };
        ApiResponseSalesReportDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SalesReportDto"];
            timestamp?: string;
        };
        DailyRevenue: {
            date?: string;
            /** Format: double */
            revenue?: number;
            /** Format: int64 */
            orderCount?: number;
        };
        SalesReportDto: {
            startDate?: string;
            endDate?: string;
            generatedAt?: string;
            /** Format: int64 */
            totalOrders?: number;
            /** Format: int64 */
            deliveredOrders?: number;
            /** Format: int64 */
            cancelledOrders?: number;
            /** Format: int64 */
            failedPaymentOrders?: number;
            /** Format: double */
            totalRevenue?: number;
            /** Format: double */
            averageOrderValue?: number;
            topMedicines?: components["schemas"]["TopMedicine"][];
            dailyRevenue?: components["schemas"]["DailyRevenue"][];
        };
        TopMedicine: {
            name?: string;
            /** Format: int64 */
            quantitySold?: number;
            /** Format: double */
            revenue?: number;
        };
        ApiResponseMapStringLong: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: number;
            };
            timestamp?: string;
        };
        ApiResponseInventoryReportDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["InventoryReportDto"];
            timestamp?: string;
        };
        InventoryReportDto: {
            generatedAt?: string;
            /** Format: int64 */
            totalMedicines?: number;
            /** Format: int64 */
            outOfStockCount?: number;
            /** Format: int64 */
            lowStockCount?: number;
            /** Format: int64 */
            expiringIn30DaysCount?: number;
            /** Format: int64 */
            alreadyExpiredCount?: number;
            /** Format: double */
            totalInventoryValue?: number;
            lowStockItems?: components["schemas"]["MedicineInventoryItem"][];
            expiringItems?: components["schemas"]["MedicineInventoryItem"][];
        };
        MedicineInventoryItem: {
            /** Format: int64 */
            id?: number;
            name?: string;
            sku?: string;
            /** Format: int32 */
            stock?: number;
            /** Format: double */
            price?: number;
            expiryDate?: string;
            categoryName?: string;
        };
        ApiResponseListPrescriptionResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PrescriptionResponseDto"][];
            timestamp?: string;
        };
        ApiResponseListOrderResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["OrderResponseDto"][];
            timestamp?: string;
        };
        ApiResponseListMedicineResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MedicineResponseDto"][];
            timestamp?: string;
        };
        ApiResponseMapStringInteger: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: number;
            };
            timestamp?: string;
        };
        ApiResponseDashboardResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["DashboardResponseDto"];
            timestamp?: string;
        };
        DashboardResponseDto: {
            /** Format: int64 */
            totalOrders?: number;
            /** Format: int64 */
            pendingPaymentOrders?: number;
            /** Format: int64 */
            packedOrders?: number;
            /** Format: int64 */
            outForDeliveryOrders?: number;
            /** Format: int64 */
            deliveredOrders?: number;
            /** Format: int64 */
            cancelledOrders?: number;
            /** Format: int64 */
            pendingPrescriptions?: number;
            /** Format: int64 */
            approvedPrescriptions?: number;
            /** Format: int64 */
            rejectedPrescriptions?: number;
            /** Format: int64 */
            totalMedicines?: number;
            /** Format: int64 */
            activeMedicines?: number;
            /** Format: int64 */
            lowStockCount?: number;
            /** Format: int64 */
            expiringThisMonthCount?: number;
            /** Format: double */
            totalRevenue?: number;
            /** Format: double */
            revenueThisMonth?: number;
            /** Format: double */
            revenueToday?: number;
            lowStockAlerts?: components["schemas"]["LowStockAlert"][];
            expiryAlerts?: components["schemas"]["ExpiryAlert"][];
            recentOrders?: components["schemas"]["RecentOrder"][];
        };
        ExpiryAlert: {
            /** Format: int64 */
            medicineId?: number;
            medicineName?: string;
            expiryDate?: string;
            /** Format: int32 */
            stock?: number;
        };
        LowStockAlert: {
            /** Format: int64 */
            medicineId?: number;
            medicineName?: string;
            /** Format: int32 */
            currentStock?: number;
        };
        RecentOrder: {
            /** Format: int64 */
            orderId?: number;
            userEmail?: string;
            status?: string;
            /** Format: double */
            totalAmount?: number;
            createdAt?: string;
        };
        ApiResponseListCategoryResponseDto: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CategoryResponseDto"][];
            timestamp?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: Record<string, never>;
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reviewPrescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrescriptionReviewDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrescriptionResponseDto"];
                };
            };
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdateDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponseDto"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: {
                reason?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponseDto"];
                };
            };
        };
    };
    getMedicineById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineResponseDto"];
                };
            };
        };
    };
    updateMedicine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicineRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineResponseDto"];
                };
            };
        };
    };
    deleteMedicine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getCategoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryResponseDto"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryResponseDto"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAllMedicines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    addMedicine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicineRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineResponseDto"];
                };
            };
        };
    };
    getAllCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryResponseDto"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryResponseDto"];
                };
            };
        };
    };
    updateStock: {
        parameters: {
            query: {
                /** @description New stock count (>= 0) */
                stock: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineResponseDto"];
                };
            };
        };
    };
    getSalesReport: {
        parameters: {
            query: {
                /** @description Start date (yyyy-MM-dd) */
                startDate: string;
                /** @description End date (yyyy-MM-dd) */
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalesReportDto"];
                };
            };
        };
    };
    getTodaySalesReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalesReportDto"];
                };
            };
        };
    };
    getThisMonthSalesReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSalesReportDto"];
                };
            };
        };
    };
    getPrescriptionReport: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringLong"];
                };
            };
        };
    };
    getInventoryReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInventoryReportDto"];
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query: {
                format: string;
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    getAllPrescriptions: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPrescriptionResponseDto"];
                };
            };
        };
    };
    getPrescriptionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrescriptionResponseDto"];
                };
            };
        };
    };
    getPendingPrescriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPrescriptionResponseDto"];
                };
            };
        };
    };
    getPrescriptionCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringLong"];
                };
            };
        };
    };
    getAllOrders: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListOrderResponseDto"];
                };
            };
        };
    };
    getOrderById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOrderResponseDto"];
                };
            };
        };
    };
    getOrdersByUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListOrderResponseDto"];
                };
            };
        };
    };
    getOrdersByStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                status: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListOrderResponseDto"];
                };
            };
        };
    };
    getActiveOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListOrderResponseDto"];
                };
            };
        };
    };
    searchMedicines: {
        parameters: {
            query: {
                q: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    getMedicinesByCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    getAlertSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringInteger"];
                };
            };
        };
    };
    getLowStockMedicines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    getExpiringMedicines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    getExpiredMedicines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    getActiveMedicines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMedicineResponseDto"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardResponseDto"];
                };
            };
        };
    };
    getActiveCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryResponseDto"];
                };
            };
        };
    };
}
