/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog/prescriptions/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Approve or reject a prescription
         * @description Required access: AUTHENTICATED.
         */
        put: operations["reviewPrescription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/prescriptions/{id}/link-order/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Required access: AUTHENTICATED. */
        put: operations["linkPrescriptionToOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/medicines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get medicine details by ID
         * @description Required access: PUBLIC.
         */
        get: operations["getMedicineById"];
        /**
         * Update a medicine (Admin only)
         * @description Required access: ADMIN.
         */
        put: operations["updateMedicine"];
        post?: never;
        /**
         * Soft-delete a medicine (Admin only)
         * @description Required access: ADMIN.
         */
        delete: operations["deleteMedicine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/prescriptions/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a prescription file
         * @description Required access: CUSTOMER.
         */
        post: operations["uploadPrescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/medicines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all medicines with optional search and filter
         * @description Required access: PUBLIC.
         */
        get: operations["getAllMedicines"];
        put?: never;
        /**
         * Create a new medicine (Admin only)
         * @description Required access: ADMIN.
         */
        post: operations["createMedicine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/inventory/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Required access: AUTHENTICATED. */
        post: operations["reserveInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/prescriptions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: AUTHENTICATED. */
        get: operations["getPrescriptionStatusForCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/prescriptions/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: ADMIN. */
        get: operations["getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/prescriptions/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: CUSTOMER. */
        get: operations["getMyPrescriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all active categories
         * @description Required access: PUBLIC.
         */
        get: operations["getAllCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category by ID
         * @description Required access: PUBLIC.
         */
        get: operations["getCategoryById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: ADMIN. */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponsePrescriptionResponseDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PrescriptionResponseDTO"];
            /** Format: date-time */
            timestamp?: string;
        };
        PrescriptionResponseDTO: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            customerId?: number;
            fileName?: string;
            fileType?: string;
            /** Format: int64 */
            fileSize?: number;
            status?: string;
            reviewNotes?: string;
            /** Format: date-time */
            uploadedAt?: string;
            /** Format: date-time */
            reviewedAt?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: Record<string, never>;
            /** Format: date-time */
            timestamp?: string;
        };
        MedicineDTO: {
            /** Format: int64 */
            id?: number;
            name: string;
            manufacturer: string;
            description?: string;
            price: number;
            discountedPrice?: number;
            /** Format: int32 */
            stock: number;
            requiresPrescription?: boolean;
            dosageInfo?: string;
            sideEffects?: string;
            imageUrl?: string;
            /** Format: date */
            expiryDate?: string;
            status?: string;
            /** Format: int64 */
            categoryId: number;
            categoryName?: string;
        };
        ApiResponseMedicineDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MedicineDTO"];
            /** Format: date-time */
            timestamp?: string;
        };
        InventoryReservationRequest: {
            /** Format: int64 */
            orderId?: number;
            items: components["schemas"]["LineItem"][];
        };
        LineItem: {
            /** Format: int64 */
            medicineId: number;
            /** Format: int32 */
            quantity: number;
        };
        ApiResponseInventoryReservationResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["InventoryReservationResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        InventoryReservationResponse: {
            /** Format: int64 */
            orderId?: number;
            /** Format: int32 */
            reservedLines?: number;
            /** Format: int32 */
            totalUnitsReserved?: number;
        };
        ApiResponseString: {
            success?: boolean;
            message?: string;
            data?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListPrescriptionResponseDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PrescriptionResponseDTO"][];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponsePageMedicineDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageMedicineDTO"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageMedicineDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            first?: boolean;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["MedicineDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
        };
        SortObject: {
            sorted?: boolean;
            empty?: boolean;
            unsorted?: boolean;
        };
        ApiResponseListCategoryDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CategoryDTO"][];
            /** Format: date-time */
            timestamp?: string;
        };
        CategoryDTO: {
            /** Format: int64 */
            id?: number;
            name: string;
            description?: string;
            iconUrl?: string;
            isActive?: boolean;
        };
        ApiResponseCategoryDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CategoryDTO"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseCatalogAdminStatsDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CatalogAdminStatsDTO"];
            /** Format: date-time */
            timestamp?: string;
        };
        CatalogAdminStatsDTO: {
            /** Format: int64 */
            totalMedicines?: number;
            /** Format: int64 */
            activeMedicines?: number;
            /** Format: int64 */
            lowStockCount?: number;
            /** Format: int64 */
            expiringIn30DaysCount?: number;
            /** Format: int64 */
            alreadyExpiredCount?: number;
            /** Format: double */
            totalInventoryValue?: number;
            /** Format: int64 */
            pendingPrescriptions?: number;
            /** Format: int64 */
            approvedPrescriptions?: number;
            /** Format: int64 */
            rejectedPrescriptions?: number;
            lowStockItems?: components["schemas"]["MedicineInventoryItem"][];
            expiringItems?: components["schemas"]["MedicineInventoryItem"][];
        };
        MedicineInventoryItem: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int32 */
            stock?: number;
            price?: number;
            expiryDate?: string;
            categoryName?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reviewPrescription: {
        parameters: {
            query: {
                status: string;
                notes?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrescriptionResponseDTO"];
                };
            };
        };
    };
    linkPrescriptionToOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getMedicineById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineDTO"];
                };
            };
        };
    };
    updateMedicine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicineDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineDTO"];
                };
            };
        };
    };
    deleteMedicine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    uploadPrescription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrescriptionResponseDTO"];
                };
            };
        };
    };
    getAllMedicines: {
        parameters: {
            query?: {
                keyword?: string;
                categoryId?: number;
                requiresPrescription?: boolean;
                page?: number;
                size?: number;
                sortBy?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageMedicineDTO"];
                };
            };
        };
    };
    createMedicine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicineDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMedicineDTO"];
                };
            };
        };
    };
    reserveInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryReservationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInventoryReservationResponse"];
                };
            };
        };
    };
    getPrescriptionStatusForCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getPending: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPrescriptionResponseDTO"];
                };
            };
        };
    };
    getMyPrescriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPrescriptionResponseDTO"];
                };
            };
        };
    };
    getAllCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryDTO"];
                };
            };
        };
    };
    getCategoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryDTO"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCatalogAdminStatsDTO"];
                };
            };
        };
    };
}
