/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Required access: AUTHENTICATED. */
        put: operations["cancelOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/cart/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Required access: AUTHENTICATED. */
        put: operations["updateQuantity"];
        post?: never;
        /** @description Required access: AUTHENTICATED. */
        delete: operations["removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/admin/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Required access: ADMIN. */
        put: operations["updateStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Required access: AUTHENTICATED. */
        post: operations["reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/payments/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Required access: AUTHENTICATED. */
        post: operations["initiatePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/checkout/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Required access: AUTHENTICATED. */
        post: operations["startCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: AUTHENTICATED. */
        get: operations["getCart"];
        put?: never;
        /** @description Required access: AUTHENTICATED. */
        post: operations["addToCart"];
        /** @description Required access: AUTHENTICATED. */
        delete: operations["clearCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: AUTHENTICATED. */
        get: operations["getMyAddresses"];
        put?: never;
        /** @description Required access: AUTHENTICATED. */
        post: operations["addAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: AUTHENTICATED. */
        get: operations["getMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: AUTHENTICATED. */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: ADMIN. */
        get: operations["getAllOrdersForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Required access: AUTHENTICATED. */
        get: operations["getAddressById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrderItemResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            medicineId?: number;
            medicineName?: string;
            /** Format: int32 */
            quantity?: number;
            unitPrice?: number;
            /** Renamed from subtotal in backend v2 */
            totalPrice?: number;
            subtotal?: number;
        };
        OrderResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            userName?: string;
            userEmail?: string;
            /** @enum {string} */
            status?: "DRAFT" | "CHECKOUT_STARTED" | "PRESCRIPTION_PENDING" | "PRESCRIPTION_APPROVED" | "PRESCRIPTION_REJECTED" | "PAYMENT_PENDING" | "PAID" | "PACKED" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CUSTOMER_CANCELLED" | "ADMIN_CANCELLED" | "PAYMENT_FAILED" | "RETURN_REQUESTED" | "REFUND_INITIATED" | "REFUND_COMPLETED";
            deliveryAddress?: string;
            deliverySlot?: string;
            pincode?: string;
            totalAmount?: number;
            finalAmount?: number;
            paymentMethod?: string;
            paymentId?: string;
            /** Format: int64 */
            prescriptionId?: number;
            /** Format: date-time */
            createdAt?: string;
            items?: components["schemas"]["OrderItemResponse"][];
        };
        CartItemResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            medicineId?: number;
            medicineName?: string;
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
            lineTotal?: number;
            requiresPrescription?: boolean;
            substituteAllowed?: boolean;
        };
        CartResponse: {
            items?: components["schemas"]["CartItemResponse"][];
            /** Format: int32 */
            totalItems?: number;
            subtotal?: number;
            hasRxItems?: boolean;
        };
        PaymentRequest: {
            /** Format: int64 */
            orderId: number;
            method: string;
            transactionRef?: string;
        };
        PaymentResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            orderId?: number;
            /** @enum {string} */
            status?: "PENDING" | "SUCCESS" | "FAILED" | "REFUNDED";
            method?: string;
            transactionId?: string;
            amount?: number;
            message?: string;
        };
        CheckoutRequest: {
            /** Format: int64 */
            addressId?: number;
            newAddress?: components["schemas"]["UserAddressRequest"];
            deliverySlot: string;
            /** Format: int64 */
            prescriptionId?: number;
        };
        UserAddressRequest: {
            streetAddress: string;
            city: string;
            state: string;
            /** Format: int32 */
            pincode?: number;
            isDefault?: boolean;
        };
        AddToCartRequest: {
            /** Format: int64 */
            medicineId: number;
            /** Format: int32 */
            quantity?: number;
            substituteAllowed?: boolean;
        };
        UserAddressResponse: {
            /** Format: int64 */
            id?: number;
            streetAddress?: string;
            city?: string;
            state?: string;
            /** Format: int32 */
            pincode?: number;
            isDefault?: boolean;
            contactPhone?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cancelOrder: {
        parameters: {
            query?: {
                reason?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    updateQuantity: {
        parameters: {
            query: {
                quantity: number;
            };
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateStatus: {
        parameters: {
            query: {
                status: "DRAFT" | "CHECKOUT_STARTED" | "PRESCRIPTION_PENDING" | "PRESCRIPTION_APPROVED" | "PRESCRIPTION_REJECTED" | "PAYMENT_PENDING" | "PAID" | "PACKED" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CUSTOMER_CANCELLED" | "ADMIN_CANCELLED" | "PAYMENT_FAILED" | "RETURN_REQUESTED" | "REFUND_INITIATED" | "REFUND_COMPLETED";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    reorder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    initiatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaymentResponse"];
                };
            };
        };
    };
    startCheckout: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CartResponse"];
                };
            };
        };
    };
    addToCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToCartRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    clearCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyAddresses: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserAddressResponse"][];
                };
            };
        };
    };
    addAddress: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAddressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserAddressResponse"];
                };
            };
        };
    };
    getMyOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"][];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    getAllOrdersForAdmin: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrderResponse"][];
                };
            };
        };
    };
    getAddressById: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                addressId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserAddressResponse"];
                };
            };
        };
    };
}
